---
apiVersion: v1
kind: Namespace
metadata:
  name: default

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-fluentd-config
  namespace: default
data:
  fluentd.conf: |
    <source>
      @type tail
      path /usr/share/elasticsearch/logs/*.log
      pos_file /tmp/log.pos
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<msg>.*)$/
      </parse>
      tag graylog2
    </source>

    <filter graylog2.**>
      @type record_transformer
      <record>
        facility "elasticsearch"
        component "elasticsearch"
        facet "elasticsearch"
        tag ${tag}
        namespace "default"
      </record>
    </filter>

    <match graylog2.**>
      @type gelf
      host graylog 
      port 12201
      protocol udp
    </match>

---
apiVersion: v1
kind: Secret
metadata:
  name: es-secret
  namespace: default
type: Opaque
stringData:
  esURI: http://customer-abc-headless:9200

---
apiVersion: v1
kind: Service
metadata:
  name: customer-abc-elasticsearch
  namespace: default
  labels:
    app: customer-abc-elasticsearch
spec:
  type: ClusterIP
  selector:
    app: customer-abc-elasticsearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
  - name: metrics
    port: 9114

---
apiVersion: v1
kind: Service
metadata:
  name: customer-abc-elasticsearch-headless
  namespace: default
  labels:
    app: customer-abc-elasticsearch
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: customer-abc-elasticsearch
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  - name: metrics
    port: 9114

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: customer-abc-elasticsearch
  namespace: default
  labels:
    app: customer-abc-elasticsearch
  annotations:
    esMajorVersion: "7"
spec:
  serviceName: customer-abc-elasticsearch-headless
  selector:
    matchLabels:
      app: customer-abc-elasticsearch
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: customer-abc-elasticsearch
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
  template:
    metadata:
      labels:
        app: customer-abc-elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 120
      initContainers:
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
          privileged: true
        image: elasticsearch:7.17.3
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        resources:
          limits:
            cpu: 25m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 128Mi
      containers:
      - name: elasticsearch
        image: elasticsearch:7.17.3
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          requests:
            cpu: "0.2"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.initial_master_nodes
          value: customer-abc-elasticsearch-0,customer-abc-elasticsearch-1,customer-abc-elasticsearch-2,
        - name: discovery.seed_hosts
          value: customer-abc-elasticsearch-headless
        - name: cluster.name
          value: customer-abc-elasticsearch
        - name: network.host
          value: "0.0.0.0"
        - name: cluster.deprecation_indexing.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xmx1g -Xms1g"
        - name: node.data
          value: "true"
        - name: node.ingest
          value: "true"
        - name: node.master
          value: "true"
        - name: node.ml
          value: "true"
        - name: node.remote_cluster_client
          value: "true"
        volumeMounts:
        - name: customer-abc-elasticsearch
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-log
          mountPath: /usr/share/elasticsearch/logs
      - name: elasticsearch-exporter
        image: elasticsearch-exporter:1.5.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: ES_URI
          valueFrom:
            secretKeyRef:
              name: es-secret
              key: esURI
        ports:
        - containerPort: 9114
      - name: elasticsearch-logrotate
        image: logrotate-1.3:1.0.1
        resources:
          requests:
            cpu: "0.05"
            memory: 200Mi
          limits:
            cpu: "0.05"
            memory: 200Mi
        env:
        - name: LOGS_DIRECTORIES
          value: '/usr/share/elasticsearch/logs'
        - name: LOGROTATE_INTERVAL
          value: 'hourly'
        - name: LOGROTATE_COPIES
          value: '1'
        - name: LOGROTATE_POSTROTATE_COMMAND
          value: 'pkill -SIGUSR1 elasticsearch >/dev/null 2>&1'
        - name: LOGROTATE_SIZE
          value: 10M
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/logs/
          name: elasticsearch-log
      - name: elasticsearch-fluentd
        image: fluentd:v1.14.3-debian-1.0-0
        resources:
          requests:
            cpu: "0.01"
            memory: 149Mi
          limits:
            cpu: "0.1"
            memory: 149Mi
        args:
        - "-c"
        - /etc/fluentd-config/fluentd.conf
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/logs/
          name: elasticsearch-log
        - mountPath: /etc/fluentd-config/fluentd.conf
          name: config-volume
          subPath: fluentd.conf
      volumes:
      - name: elasticsearch-log
        emptyDir: {}
      - name: config-volume
        configMap:
          name: elasticsearch-fluentd-config
